### ISSUE TITLE
Typos in timely dataflow post

### ISSUE THREAD

**Issue by ms705** [frankmcsherry/frankmcsherry.github.io#1]
Nice post! Two (likely editing-related) typos hit my eye as I was reading.

See https://gist.github.com/ms705/dc4cf783a359c4eb1089 for a patch.

**Comment by frankmcsherry** [comment]
Thanks! First is totally an editing error, the second one, who knows? :D

**Comment by ms705** [comment]
On that note, I added a third one (missing genitive, although its use does destroy the nice "Subgraphs may ..." pattern!). Gist updated.

BTW, one comment regarding the coordination logic vs. computation logic language point: our experience with CIEL was that people are really, really unkeen on the idea of implementing their coordination in a different language to the computation, so caution might be necessary here. Then again, we did ask them to use a bespoke DSL without proper error reporting, so this may not exactly be a representative study ;-)

**Comment by frankmcsherry** [comment]
I think the plan with “coordination vs computation” is that if you want to use Java, I (or some benevolent soul) provides a very small bit of timely dataflow code in Java that you snag as your only real dependence in the project for your vertex. The general-purpose Rust code chats with the wrapper (which is basically acting as a mini-scheduler for your vertex), and ideally, from the programmers point of view, it isn’t too much different than just having a Java Naiad implementation around your vertex. It does lose the “language integrated” part, but.. 

My experience was that everyone and their uncle wanted the ability to use a different language, be it python or java or C or whatever. Or they have libraries already in those languages, and would love to pull them in, but don’t know what to do. I suppose one goal here is to let that happen and see what the pain points are. I can imagine that “dataflow assembly” might become the main pain point (is this what you meant by coordination, or something else?), which I suspect leads down the path of “well, here is an xml format for dataflow graphs and … sigh…”, or maybe “here is Rust, which you don’t understand, but just copy/paste these things”.

I was sort of hoping processes would be a good boundary for timely dataflow stuff, where you just said “hey, I don’t know how the vertex works, but just run this process”. If that actually works out (deep language integration be damned) then porting it to a few different languages should be pretty easy, right? >.<  Maybe a better next step at this point would be crystalizing the inter-vertex protocol (it exists, and is great, but may not be as flexible as possible) at which point other folks can step up as needed. Future blog post!

Thanks again for the typos, and the musings.
